using Model;

namespace StubLib;

public class Stub: ILoader
{
    private readonly List<Album> _albums = new()
    {
        new Album(
            "Speak No Evil(RUdy Van Gelder Edition)",
            "Wayne Shorter", "speak_no_evil",
            "Jazz", new DateTime(1966, 1, 1),
            "&#8471; 1966 Blue Note Records",
            "Lossless",
            false,
            48,
            new Music(1, "Witch Hunt", true),
            new Music(2, "Fee-Fi-Fo-Fum", false),
            new Music(3, "Dance Cadaverous", false),
            new Music(4, "Speak No Evil", false),
            new Music(5, "Infant Eyes", false),
            new Music(6, "Wild Flower", false),
            new Music(7, "Dance Cadaverous (Alternate Take)", false)
        ),
        new Album(
            "Highway to Hell",
            "AC/DC", 
            "highway_to_hell",
            "Hard Rock",
            new DateTime(1979, 7, 27),
            "&#8471; 1979 Leidseplein Presse B.V. for U.S. and Australian Music Corporation Ltd. for the rest of the world",
            "Lossless Haute Qualité",
            true,
            41,
            new Music(1, "Highway to Hell", true),
            new Music(2, "Girls Got Rhythm", false),
            new Music(3, "Walk All Over You", false),
            new Music(4, "Touch Too Much", false),
            new Music(5, "Beating Around the Bush", false),
            new Music(6, "Shot Down in Flames", false),
            new Music(7, "Get It Hot", false),
            new Music(8, "If You Want Blood (You've Got It)", false),
            new Music(9, "Love Hungry Man", false),
            new Music(10, "Night Prowler", false)
        ),
        new Album(
            "Nevermind",
            "Nirvana",
            "nevermind",
            "Alternavie",
            new DateTime(1991, 9, 24),
            "&#8471; 2011 Geffen Records",
            "Lossless",
            true,
            49,
            new Music(1, "Smells Like Teen Spirit", true),
            new Music(2, "In Bloom", false),
            new Music(3, "Come as You Are", true),
            new Music(4, "Breed", false),
            new Music(5, "Lithium", false),
            new Music(6, "Polly", false),
            new Music(7, "Territorial Pissings", false),
            new Music(8, "Drain You", false),
            new Music(9, "Lounge Act", false),
            new Music(10, "Stay Away", false),
            new Music(11, "On a Plain", false),
            new Music(12, "Something in the Way", false),
            new Music(13, "Endless, Nameless", false)
        ),
        new Album(
            "POST HUMAN: SURVIVAL HORROR",
            "Bring Me The Horizon",
            "post_human_survival_horror",
            "Hard Rock",
            new DateTime(2020, 10, 30),
            "&#8471; 2020 Sony Music Entertainment UK Limited",
            "Lossless",
            false,
            32,
            new Music(1, "Dear Diary,", false),
            new Music(2, "Parasite Eve", false),
            new Music(3, "Teardrops", true),
            new Music(4, "Obey(with YUNGBLUD)", false),
            new Music(5, "Itch for the Cure (When Will We Be Free?)", false),
            new Music(6, "Kingslayer(with BABYMETAL)", true),
            new Music(7, "1x1(with Nova Twins)", false),
            new Music(8, "Ludens", false),
            new Music(9, "One Day the Only Butterflies Left Will Be in Your Chest as You March Towards Your Death(with Amy Lee)", false)
        ),
        new Album(
            "Rammstein",
            "Rammstein",
            "rammstein",
            "Metal",
            new DateTime(2019, 5, 17),
            "A Vertigo/Capitol release; &#8471; 2019 Rammstein GBR, under exclusive license to Universal Music GmbH",
            "Lossless haute qualité",
            true,
            46,
            new Music(1, "Deutschland", true),
            new Music(2, "Radio", true),
            new Music(3, "Zeig dich", false),
            new Music(4, "Ausländer", true),
            new Music(5, "Sex", false),
            new Music(6, "Puppe", false),
            new Music(7, "Was ich liebe", false),
            new Music(8, "Diamant", false),
            new Music(9, "Weit weg", false),
            new Music(10, "Tattoo", false),
            new Music(11, "Hallomann", false)
        ),
        new Album(
            "Machine Head (Remastered)",
            "Deep Purple",
            "machine_head",
            "Hard Rock",
            new DateTime(1972, 3, 25),
            "&#8471; 2015 Deep Purple (Overseas) Ltd. under exclusive license to Universal Music Group Ltd.",
            "Lossless",
            true,
            37,
            new Music(1, "Highway Star (Remastered)", true),
            new Music(2, "Maybe I'm a Leo (Remastered)", false),
            new Music(3, "Pictures of Home (Remastered)", false),
            new Music(4, "Never Before (Remastered)", false),
            new Music(5, "Smoke on the Water (Remastered)", true),
            new Music(6, "Lazy (Remastered)", false),
            new Music(7, "Space Truckin' (Remastered)", false)
        ),
        new Album(
            "RUSH!",
            "Måneskin",
            "rush",
            "Rock",
            new DateTime(2023, 01, 20),
            "&#8471; An Epic release (P) 2021 Sony Music Entertainment Italy S.p.a.",
            "Lossless",
            false,
            52,
            new Music(1, "OWN MY MIND", false),
            new Music(2, "Gossip (feat. Tom Morello)", false),
            new Music(3, "TIMEZONE", false),
            new Music(4, "BLA BLA BLA", false),
            new Music(5, "BABY SAID", true),
            new Music(6, "GASOLINE", false),
            new Music(7, "FEEL", false),
            new Music(8, "DON'T WANNA SLEEP", false),
            new Music(9, "KOOL KIDS", false),
            new Music(10, "IF NOT FOR YOU", false),
            new Music(11, "READ YOUR DIARY", false),
            new Music(12, "MARK CHAPMAN", false),
            new Music(13, "LA FINE", false),
            new Music(14, "IL DONO DELLA VITA", false),
            new Music(15, "MAMMAMIA", false),
            new Music(16, "SUPERMODEL", false),
            new Music(17, "THE LONELIEST", true)
        ),  
        new Album(
            "Kaioty - EP",
            "Tip Stevens",
            "kaioty",
            "Rock",
            new DateTime(2022, 10, 24),
            "&#8471; 2022 Floral Records x Minuit 14",
            "Lossless",
            false,
            20, 
            new Music(1, "Miracle", true),
            new Music(2, "The Remedy", false),
            new Music(3, "Stay in Your Cage", false),
            new Music(4, "Ember", false),
            new Music(5, "Kaioty", false)
        )   
    };
    
    public IEnumerable<Album> Load() => _albums;
}
