using Model;

namespace Stub;

public class Stub: ILoader
{
    private readonly List<Album> _albums = new()
    {
        new Album(
            "Speak No Evil(RUdy Van Gelder Edition)",
            "Wayne Shorter", "speak_no_evil",
            "Jazz", new DateTime(1966, 1, 1),
            "&#8471; 1966 Blue Note Records",
            "Lossless",
            false,
            48,
            new(1, "Witch Hunt"),
            new(2, "Fee-Fi-Fo-Fum"),
            new(3, "Dance Cadaverous"),
            new(4, "Speak No Evil"),
            new(5, "Infant Eyes"),
            new(6, "Wild Flower"),
            new(7, "Dance Cadaverous (Alternate Take)")
        ),
        new Album(
            "Highway to Hell",
            "AC/DC", 
            "highway_to_hell",
            "Hard Rock",
            new DateTime(1979, 7, 27),
            "&#8471; 1979 Leidseplein Presse B.V. for U.S. and Australian Music Corporation Ltd. for the rest of the world",
            "Lossless Haute Qualité",
            true,
            41,
            new(1, "Highway to Hell"),
            new (2, "Girls Got Rhythm"),
            new (3, "Walk All Over You"),
            new (4, "Touch Too Much"),
            new (5, "Beating Around the Bush"),
            new (6, "Shot Down in Flames"),
            new (7, "Get It Hot"),
            new (8, "If You Want Blood (You've Got It)"),
            new (9, "Love Hungry Man"),
            new (10, "Night Prowler")
        ),
        new Album(
            "Nevermind",
            "Nirvana",
            "nevermind",
            "Alternavie",
            new DateTime(1991, 9, 24),
            "&#8471; 2011 Geffen Records",
            "Lossless",
            true,
            49,
            new(1, "Smells Like Teen Spirit"),
            new(2, "In Bloom"),
            new(3, "Come as You Are"),
            new(4, "Breed"),
            new(5, "Lithium"),
            new(6, "Polly"),
            new(7, "Territorial Pissings"),
            new(8, "Drain You"),
            new(9, "Lounge Act"),
            new(10, "Stay Away"),
            new(11, "On a Plain"),
            new(12, "Something in the Way"),
            new(13, "Endless, Nameless")
        ),
        new Album(
            "POST HUMAN: SURVIVAL HORROR",
            "Bring Me The Horizon",
            "post_human_survival_horror",
            "Hard Rock",
            new DateTime(2020, 10, 30),
            "&#8471; 2020 Sony Music Entertainment UK Limited",
            "Lossless",
            false,
            32,
            new(1, "Dear Diary,"),
            new(2, "Parasite Eve"),
            new(3, "Teardrops"),
            new(4, "Obey(with YUNGBLUD)"),
            new(5, "Itch for the Cure (When Will We Be Free?)"),
            new(6, "Kingslayer(with BABYMETAL)"),
            new(7, "1x1(with Nova Twins)"),
            new(8, "Ludens"),
            new(9, "One Day the Only Butterflies Left Will Be in Your Chest as You March Towards Your Death(with Amy Lee)")
        ),
        new Album(
            "Rammstein",
            "Rammstein",
            "rammstein",
            "Metal",
            new DateTime(2019, 5, 17),
            "A Vertigo/Capitol release; &#8471; 2019 Rammstein GBR, under exclusive license to Universal Music GmbH",
            "Lossless haute qualité",
            true,
            46,
            new(1, "Deutschland"),
            new(2, "Radio"),
            new(3, "Zeig dich"),
            new (4, "Ausländer"),
            new (5, "Sex"),
            new (6, "Puppe"),
            new (7, "Was ich liebe"),
            new (8, "Diamant"),
            new (9, "Weit weg"),
            new (10, "Tattoo"),
            new (11, "Hallomann")
        ),
        new Album(
            "Machine Head (Remastered)",
            "Deep Purple",
            "machine_head",
            "Hard Rock",
            new DateTime(1972, 3, 25),
            "&#8471; 2015 Deep Purple (Overseas) Ltd. under exclusive license to Universal Music Group Ltd.",
            "Lossless",
            true,
            37,
            new(1, "Highway Star (Remastered)"),
            new(2, "Maybe I'm a Leo (Remastered)"),
            new(3, "Pictures of Home (Remastered)"),
            new(4, "Never Before (Remastered)"),
            new(5, "Smoke on the Water (Remastered)"),
            new(6, "Lazy (Remastered)"),
            new(7, "Space Truckin' (Remastered)")
        ),
        new Album(
            "RUSH!",
            "Måneskin",
            "rush",
            "Rock",
            new DateTime(2023, 01, 20),
            "&#8471; An Epic release (P) 2021 Sony Music Entertainment Italy S.p.a.",
            "Lossless",
            false,
            52,
            new(1, "OWN MY MIND"),
            new (2, "Gossip (feat. Tom Morello)"),
            new (3, "TIMEZONE"),
            new (4, "BLA BLA BLA"),
            new (5, "BABY SAID"),
            new (6, "GASOLINE"),
            new (7, "FEEL"),
            new (8, "DON'T WANNA SLEEP"),
            new (9, "KOOL KIDS"),
            new (10, "IF NOT FOR YOU"),
            new (11, "READ YOUR DIARY"),
            new (12, "MARK CHAPMAN"),
            new (13, "LA FINE"),
            new (14, "IL DONO DELLA VITA"),
            new (15, "MAMMAMIA"),
            new (16, "SUPERMODEL"),
            new (17, "THE LONELIEST")
        ),
        new Album(
            "Kaioty - EP",
            "Tip Stevens",
            "kaioty",
            "Rock",
            new DateTime(2022, 10, 24),
            "&#8471; 2022 Floral Records x Minuit 14",
            "Lossless",
            false,
            20,
            new(1, "Miracle"),
            new(2, "The Remedy"),
            new(3, "Stay in Your Cage"),
            new(4, "Ember"),
            new(5, "Kaioty")
        )
    };
    
    public IEnumerable<Album> Load() => _albums;
}
